# -*- coding: utf-8 -*-
"""
Usage:

    Add this file to directory 'pywikibot/families/'.

---

This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://questionablecontent.fandom.com/
  name = qcwiki

"""
from __future__ import absolute_import, division, unicode_literals

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):  # noqa: D101

    name = 'qcwiki'
    langs = {
        'en': 'questionablecontent.fandom.com',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': '1.19.24',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
